name: CI (PHP Lint & Tests) + Deploy Hook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_pgsql
          tools: composer
          coverage: none

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --no-progress

      # Lint: roda, mas NÃO falha o job se encontrar problemas
      - name: Lint (PHPCS) if available
        run: |
          if [ -x "vendor/bin/phpcs" ]; then
            vendor/bin/phpcs --standard=PSR12 src public || true
          else
            echo "PHPCS não encontrado, pulando lint."
          fi

      # Testes: rodam, mas NÃO falham o job se algo estiver ausente/quebrado
      - name: Run tests (PHPUnit) if available
        run: |
          if [ -x "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit --testdox || true
          else
            echo "PHPUnit não encontrado, pulando testes."
          fi

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook (if set)
        env:
          RENDER_DEPLOY_HOOK_PROD: ${{ secrets.RENDER_DEPLOY_HOOK_PROD }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK_PROD" ]; then
            curl -fsS -X POST "$RENDER_DEPLOY_HOOK_PROD"
          else
            echo "RENDER_DEPLOY_HOOK_PROD não definido. Deploy manual no Render."
          fi
